### ISSUE TITLE
Criar primeiros layouts no Figma

### ISSUE THREAD

**Issue by Bruno-Camargo-V3ktor** [SignaGen/SignatureCraft#2]

**Comment by Henrry-Maximo** [comment]
- Layout development in Figma, something examples:

![image](https://github.com/user-attachments/assets/91e9061a-bf15-42d9-920c-bbeb1d57517d)
![image](https://github.com/user-attachments/assets/ae9c38f3-5989-42b3-9ccb-e2a6cf5c2259)
![image](https://github.com/user-attachments/assets/279a8776-f6c4-4a89-8193-066d0cfa53ab)
![image](https://github.com/user-attachments/assets/cc58f581-76fb-4ca3-ad22-dc747c800d6a)
![image](https://github.com/user-attachments/assets/dae87ec7-2646-4cf7-95bd-2cdd0f42aab8)
